version: "3.8"

services:
  web:
    depends_on: 
      - api
    container_name: frontend
    build: ./ren-salon-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./ren-salon-frontend:/app
      - /app/node_modules

  api: 
    depends_on: 
      - mysql
    container_name: backend
    build: ./ren-salon-backend
    ports: 
      - "3000:3000"
    volumes:
      - ./ren-salon-backend:/app
      - /app/node_modules

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme
    volumes:
      - mysql-data2:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: changeme
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - mysql

volumes:
  mysql-data2:
